package planning

import (
	"fmt"
	"reflect"
	"strings"
)

// PreviewRemedy validates the offered choice and computes its complete effect.
// The original inputs remain untouched (specs/017-planning-and-execution-usability.md:83).
func PreviewRemedy(in BaselineInputs, choice Remedy) (BaselineInputs, *Schedule, *Schedule, error) {
	var offered *Remedy
	for _, r := range ComputeRemedies(in.Teams, in.Initiatives, in.Params, in.Scheduling, []string{choice.Target}) {
		if reflect.DeepEqual(r, choice) {
			v := r
			offered = &v
			break
		}
	}
	if offered == nil {
		return BaselineInputs{}, nil, nil, fmt.Errorf("this remedy is no longer offered; refresh the options")
	}
	r := *offered
	out := NewBaselineInputs(in.Teams, in.Initiatives, in.Params, in.Scheduling)
	switch r.Kind {
	case "descope":
		out.Teams, out.Initiatives = ApplyLevers(out.Teams, out.Initiatives, []Lever{{Type: "descope", Initiative: r.Target, N: r.Magnitude}})
	case "add-capacity":
		out.Teams, out.Initiatives = ApplyLevers(out.Teams, out.Initiatives, []Lever{{Type: "addCapacity", Pod: r.Pod, N: r.Magnitude}})
	case "defer-other":
		// The offered note is generated by remediesFor, never accepted as an
		// arbitrary instruction from the caller. Exact matching above binds it.
		name := strings.TrimSuffix(strings.TrimPrefix(r.Note, "defer "), " out of this period")
		out.Teams, out.Initiatives = ApplyLevers(out.Teams, out.Initiatives, []Lever{{Type: "defer", Initiative: name}})
	case "raise-priority", "relax-date", "unlock":
		for i := range out.Initiatives {
			it := &out.Initiatives[i]
			if it.Name != r.Target {
				continue
			}
			switch r.Kind {
			case "raise-priority":
				it.StatedPriority, it.PriorityLocked = int(r.Magnitude), true
			case "relax-date":
				for _, si := range in.RecomputeWith(ScheduleOptions{}).Initiatives {
					if si.Name == r.Target {
						it.TargetDate = dateAtWeek(in.Scheduling.PeriodStart, si.CommitWeek)
					}
				}
			case "unlock":
				it.DateLocked = false
			}
		}
	default:
		return BaselineInputs{}, nil, nil, fmt.Errorf("unsupported remedy")
	}
	return out, in.RecomputeWith(ScheduleOptions{}), out.RecomputeWith(ScheduleOptions{}), nil
}
